<?php
/**
 * A class for storing custom fields
 */
class CustomField extends zajModel{

	/**
	 * __model function. creates the database fields available for objects of this class.
	 * @param stdClass $fields The field's object generated by the child class.
 	 * @return stdClass Returns an object containing the field settings as parameters.
	 */
	static function __model(stdClass $fields = new stdClass()) : stdClass {

		$fields->name = zajDb::name();
		$fields->type = zajDb::select(array('text', 'number'));
		$fields->featured = zajDb::boolean();
		$fields->customfieldentries = zajDb::onetomany('CustomFieldEntry', 'customfield');

		// do not modify the line below!
        return parent::__model($fields);
	}

	///////////////////////////////////////////////////////////////
	// !Custom methods
	///////////////////////////////////////////////////////////////

	public function __afterFetch(){
	}

	public static function __onSearch($fetcher){ return $fetcher; }
}