<?php
/**
 * A class for storing custom fields
 */
class CustomFieldEntry extends zajModel{

	/**
	 * __model function. creates the database fields available for objects of this class.
	 * @param stdClass $fields The field's object generated by the child class.
 	 * @return stdClass Returns an object containing the field settings as parameters.
	 */
	static function __model(stdClass $fields = new stdClass()) : stdClass {

		$fields->customfield = zajDb::manytoone('CustomField');
		$fields->value = zajDb::text();
		$fields->class = zajDb::text();
		$fields->parent = zajDb::text();
		$fields->field = zajDb::text();

		// do not modify the line below!
        return parent::__model($fields);
	}

	///////////////////////////////////////////////////////////////
	// !Custom methods
	///////////////////////////////////////////////////////////////

	public function __afterFetch(){
	}
}