<?php
/**
 * A class for storing custom fields
 */
class CustomField extends zajModel{

	/**
	 * __model function. creates the database fields available for objects of this class.
	 * @param bool|stdClass $f The field's object generated by the child class.
 	 * @return stdClass Returns an object containing the field settings as parameters.
	 */
	static function __model($f = false){
		/////////////////////////////////////////
		// begin custom fields definition:
        if($f === false) $f = new stdClass();

		$f->name = zajDb::name();
		$f->type = zajDb::select(array('text', 'number'));
		$f->featured = zajDb::boolean();
		$f->customfieldentries = zajDb::onetomany('CustomFieldEntry', 'customfield');

		// do not modify the line below!
        return parent::__model($f);
	}

	///////////////////////////////////////////////////////////////
	// !Custom methods
	///////////////////////////////////////////////////////////////

	public function __afterFetch(){
	}

	public static function __onSearch($fetcher){ return $fetcher; }
}