<?php
/**
 * A test model that extends the File model
 * @package Model
 * @subpackage BuiltinModels
 **/

class FileTest extends zajModelExtender {

	/**
	 * __model function. creates the database fields available for objects of this class.
	 * @param bool|stdClass $f The field's object generated by the child class.
 	 * @return stdClass Returns an object containing the field settings as parameters.
	 */
	public static function __model($f = false){

		/////////////////////////////////////////
		// begin custom fields definition:
        if($f === false) $f = new stdClass();

		// Don't test model fields yet

		// end of custom fields definition
		/////////////////////////////////////////

		// do not modify the line below!
        return parent::__model($f);
	}

	/**
	 * A test for a standard public method.
	 **/
	public function just_a_test(){
		return "just_a_test";
	}

	/**
	 * A test for a standard public static method.
	 **/
	public static function just_a_test_static(){
		return "just_a_test_static";
	}
}

// Extend my file
FileTest::extend('File');
