<?php
/**
 * A basic test model.
 * @package Model
 * @subpackage BuiltinModels
 **/

/**
 * Class OfwTest
 * @property OfwTestAnotherData $data
 */
class OfwTestAnother extends zajModel {

	/**
	 * __model function. creates the database fields available for objects of this class.
	 * @param bool|stdClass $f The field's object generated by the child class.
 	 * @return stdClass Returns an object containing the field settings as parameters.
	 */
	public static function __model($f = false){

		/////////////////////////////////////////
		// begin custom fields definition:
        if($f === false) $f = new stdClass();

        // Fake manytomany connection
        $f->ofwtests = zajDb::manytomany('OfwTestModel', 'ofwtestanothers');

		// end of custom fields definition
		/////////////////////////////////////////

		// do not modify the line below!
        return parent::__model($f);
	}

}
